service: dex-aggregator-api

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true

functions:
  healthcheck:
    handler: src/handler.healthcheck
    events:
      - httpApi:
          path: /healthcheck
          method: get
